#!/usr/bin/env python3
"""fleet-provision -- emit the script that recreates this fleet's OS-level setup.

WHY THIS EXISTS. Balázs, 2026-09-01: everything must be arranged so that after any restart of
us or the server, everyone and everything comes back without loss. The code and the data have
homes (a repo and a backup). The layer between them has none: the OS users each agent runs as,
the `sec-*` groups that gate their secrets, the sudoers rules that let the router reach them,
and the ACLs that decide who can write where. A container recreate keeps only the bind mount,
so all of that is lost and has to be rebuilt from memory. Today it exists nowhere but in the
running system.

It EMITS, it does not apply. Everything here needs root, and running it blind on a live fleet
would be worse than the problem. Read what it prints, then decide.

  python3 scripts/fleet-provision.py            # print the script
  python3 scripts/fleet-provision.py --write    # write store/fleet-provision.generated.sh

WHAT IT CANNOT CAPTURE, and says so rather than pretending completeness:
  * passwords and tokens -- those are the third layer, never in a file like this
  * file CONTENTS -- that is the repo's job and the backup's job
  * anything our uid cannot read

ONE FINDING THAT MADE THIS WORTH WRITING. `sec-transcripts` has exactly one member, marveen.
Yet agents write into directories owned by that group, which looks impossible from
/etc/group alone. The answer is a DEFAULT ACL granting `group:fleet:rwx`, inherited by every
new directory. On 2026-09-01 I reasoned from the permission bits alone, concluded an agent
could not write, and was refuted by that agent's own measurement. The ACLs are why, and they
are the part a rebuild silently drops.
"""

import os
import pwd
import grp
import subprocess
import sys

ROOT = os.environ.get("FLEET_ROOT", "/home/marveen/marveen")
OUT = os.path.join(ROOT, "store", "fleet-provision.generated.sh")


def run(cmd):
    try:
        p = subprocess.run(cmd, capture_output=True, text=True, timeout=20)
        return p.stdout
    except Exception:
        return ""


def agent_users():
    out = []
    for p in pwd.getpwall():
        if p.pw_name.startswith("agent-"):
            out.append(p)
    return sorted(out, key=lambda p: p.pw_uid)


def fleet_groups():
    out = []
    for g in grp.getgrall():
        if g.gr_name == "fleet" or g.gr_name.startswith("sec-"):
            out.append(g)
    return sorted(out, key=lambda g: g.gr_gid)


def build():
    L = ["#!/usr/bin/env bash",
         "# GENERATED by scripts/fleet-provision.py. Do not edit; regenerate.",
         "# Recreates the OS-level layer of the fleet: users, groups, memberships, ACLs.",
         "#",
         "# It does NOT create secrets, does NOT write file contents, and does NOT start",
         "# anything. Run it on a rebuilt machine BEFORE restoring the backup, so the",
         "# restored files land with owners that exist.",
         "#",
         "# Needs root. Read it before running it.",
         "set -euo pipefail", "",
         "if [ \"$(id -u)\" -ne 0 ]; then echo 'root kell hozza' >&2; exit 1; fi", ""]

    L += ["# --- csoportok ---",
          "# A gid szamit, nem csak a nev: a fajlok a SZAMOT hordozzak, es egy mas gid-del",
          "# ujraletrehozott csoport a visszaallitott fajlokat idegennek latja.", ""]
    for g in fleet_groups():
        L.append("getent group %s >/dev/null || groupadd -g %d %s" % (g.gr_name, g.gr_gid, g.gr_name))
    L.append("")

    L += ["# --- agens felhasznalok ---",
          "# Az elsodleges csoport (fleet) NEM latszik a /etc/group tagsagi listajaban, mert",
          "# az csak a MASODLAGOS tagokat sorolja. Ezert kell itt kiirni.", ""]
    for p in agent_users():
        gname = grp.getgrgid(p.pw_gid).gr_name
        L.append("id -u %s >/dev/null 2>&1 || useradd -u %d -g %s -m -d %s -s /bin/bash %s"
                 % (p.pw_name, p.pw_uid, gname, p.pw_dir, p.pw_name))
    L.append("")

    L += ["# --- masodlagos csoporttagsagok ---",
          "# Ezek dontik el, melyik agens melyik titkot eri el. Egy hianyzo sor nem hibat ad,",
          "# hanem egy agens csendben nem lat valamit -- 2026-09-01-en ez a fajta hiba",
          "# oraig tartott, mert nullanak latszott, nem hianynak.", ""]
    for g in fleet_groups():
        for m in sorted(g.gr_mem):
            L.append("usermod -aG %s %s" % (g.gr_name, m))
    L.append("")

    L += ["# --- ACL-ek az agens konyvtarakon ---",
          "# EZ A RESZ A LEGKONNYEBBEN ELVESZO. A jogosultsagi bitek onmagukban azt mutatjak,",
          "# hogy egy agens NEM tud irni a sajat naplo-konyvtaraba; a valosag maskepp all, mert",
          "# egy DEFAULT ACL adja meg a fleet csoportnak. Ha ez nem all vissza, az agensek",
          "# elindulnak, es a beszelgetesuk nem mentodik -- pontosan ugy, ahogy 2026-09-01-en.", ""]
    adir = os.path.join(ROOT, "agents")
    for name in sorted(os.listdir(adir)) if os.path.isdir(adir) else []:
        d = os.path.join(adir, name)
        if not os.path.isdir(d):
            continue
        acl = run(["getfacl", "-p", d])
        has_default = "default:" in acl
        L.append("# %s" % d)
        L.append("chown -R agent-%s:fleet '%s' 2>/dev/null || true" % (name, d))
        L.append("chmod -R g+rwX '%s'" % d)
        L.append("find '%s' -type d -exec chmod g+s {} +" % d)
        if has_default:
            L.append("setfacl -R -m g:fleet:rwX -m d:g:fleet:rwX '%s'" % d)
        else:
            L.append("# (ezen a konyvtaron ma nincs default ACL)")
        L.append("")

    L += ["# --- sudoers ---",
          "# A tenyleges szabalyok a repo templates/sudoers mappajabol jonnek, NEM innen:",
          "# egy generalt sudoers fajl a legrosszabb helye egy elgepelesnek. Itt csak az all,",
          "# MELYIK fajloknak kell letezniuk.", ""]
    sd = "/etc/sudoers.d"
    if os.path.isdir(sd):
        for fn in sorted(os.listdir(sd)):
            L.append("# /etc/sudoers.d/%s" % fn)
    L += ["",
          "echo 'kesz. Ellenorzes: id agent-<nev>, es getfacl az agens konyvtaran.'",
          ""]
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    text = build()
    if "--write" in sys.argv:
        os.makedirs(os.path.dirname(OUT), exist_ok=True)
        open(OUT, "w").write(text)
        os.chmod(OUT, 0o644)
        print("megirva: %s (%d sor)" % (OUT, len(text.splitlines())))
    else:
        print(text)
